pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                sh '''
                    if [ -d .git ]; then
                        echo "Repository already exists; skipping clone."
                    else
                        git clone --branch main https://github.com/Engg-Sayed-Abdul-Qayum/CI-CD.git .
                    fi
                '''
            }
        }

        stage('Docker Image Build') {
            steps {
                sh 'sudo docker build -t my-image:latest .'
            }
        }
    }
}